/**
 * Role matrix audit for the dashboard.
 *
 * Signs in as each seeded test account — completing the real two-factor
 * challenge — then walks every navigation item that role can see, clicking
 * through and recording console errors, failed requests and dead screens.
 *
 *   node e2e/roles.mjs --headed          # watch it
 *   node e2e/roles.mjs                   # headless
 *   node e2e/roles.mjs --role manager    # one role only
 *
 * Chrome is driven directly because Playwright ships no Chromium for macOS 12.
 */
import { chromium } from 'playwright';
import path from 'path';
import { createRequire } from 'module';

/**
 * Deliberately the backend's copy of otplib, not this project's.
 *
 * The server verifies codes with otplib 12, whose API differs from 13 — and a
 * code generated by a different implementation may not validate. Using the same
 * module the server uses removes any doubt about whose fault a rejection is.
 */
const { authenticator } = createRequire(import.meta.url)(
  path.resolve(process.cwd(), '..', 'hotelopsx-backend', 'node_modules', 'otplib')
);
import fs from 'fs';

const args = process.argv.slice(2);
const HEADED = args.includes('--headed');
const ONLY = args.includes('--role') ? args[args.indexOf('--role') + 1] : null;
const BASE = 'http://localhost:5173';

const CREDS = path.join(process.cwd(), '..', 'hotelopsx-backend', 'test-users.json');
const SHOTS = path.join(process.cwd(), 'e2e', 'screenshots');
fs.mkdirSync(SHOTS, { recursive: true });

const { users } = JSON.parse(fs.readFileSync(CREDS, 'utf8'));

const findings = [];
const record = (severity, role, screen, kind, detail) =>
  findings.push({ severity, role, screen, kind, detail });

/** Console noise that says nothing about application health. */
const IGNORABLE = [
  /Download the React DevTools/i,
  /\[vite\]/i,
  /React Router Future Flag/i,
  /Warning: validateDOMNesting/i,
  /was created with unknown prop/i
];

/**
 * Requests that are expected to fail for some roles.
 *
 * A 403 on a screen the role cannot reach is the permission system working, not
 * a bug — recording those would bury real failures in noise. A 401 is handled
 * separately because it means the session broke mid-run.
 */
const isExpectedDenial = (status) => status === 403;

const signIn = async (page, user) => {
  await page.goto(`${BASE}/login`, { waitUntil: 'networkidle', timeout: 30000 });

  /**
   * The login screen opens in usercode mode with a numeric keypad, so the email
   * form does not exist until the tab is switched. Matching on the exact label
   * avoids also matching the "Email" field once it appears.
   */
  const emailTab = page.getByRole('button', { name: /email & password/i }).first();
  if (await emailTab.isVisible().catch(() => false)) {
    await emailTab.click();
    await page.waitForTimeout(600);
  }

  await page.locator('input[name="email"]').fill(user.email);
  await page.locator('input[name="password"]').fill(user.password);
  await page.getByRole('button', { name: /^sign in$/i }).first().click();

  /**
   * Wait for the outcome rather than a fixed delay: either the second-factor
   * prompt appears, or navigation away from /login happens. A timeout here was
   * checking for the field before React had rendered it, which read as a failed
   * sign-in when the flow was working.
   */
  const mfaField = page.getByLabel(/authentication code/i).first();
  await Promise.race([
    mfaField.waitFor({ state: 'visible', timeout: 8000 }).catch(() => null),
    page.waitForURL((url) => !url.pathname.includes('/login'), { timeout: 8000 }).catch(() => null)
  ]);

  if (await mfaField.isVisible().catch(() => false)) {
    await mfaField.fill(authenticator.generate(user.mfaSecret));
    await page.getByRole('button', { name: /verify and sign in/i }).first().click();
    await page
      .waitForURL((url) => !url.pathname.includes('/login'), { timeout: 12000 })
      .catch(() => null);
  }

  /**
   * Wait for the session to finish establishing, not just for the redirect.
   *
   * After landing, the app fetches /auth/me and re-renders the navigation with
   * the account's effective permissions. Enumerating the menu before that
   * arrives showed an HR Manager with a single item and reported it as correct,
   * when the permission-driven entries were simply not rendered yet.
   */
  await page
    .waitForResponse((res) => res.url().includes('/auth/me') && res.status() === 200, {
      timeout: 8000
    })
    .catch(() => null);
  await page.waitForTimeout(1500);

  const url = page.url();
  const signedIn = !url.includes('/login');
  return { signedIn, landedOn: url.replace(BASE, '') || '/' };
};

const run = async () => {
  const browser = await chromium.launch({
    channel: 'chrome',
    headless: !HEADED,
    slowMo: HEADED ? 350 : 0
  });

  const targets = ONLY ? users.filter((u) => u.label === ONLY) : users;
  if (targets.length === 0) {
    console.error(`No such role: ${ONLY}`);
    process.exit(1);
  }

  console.log(`\nRole matrix — ${targets.length} role(s) against ${BASE}\n`);

  for (const user of targets) {
    // A fresh context per role: no cookie or storage carried between sessions,
    // so one role cannot mask another's permission failure.
    const context = await browser.newContext({ viewport: { width: 1440, height: 900 } });
    const page = await context.newPage();

    let screen = 'login';

    page.on('console', (msg) => {
      if (msg.type() !== 'error') return;
      const text = msg.text();
      if (IGNORABLE.some((re) => re.test(text))) return;
      // Same reason as the 401 filter below: the MFA challenge is expected.
      if (screen === 'login' && /401/.test(text)) return;
      // Same reason as the /hr/me filter below.
      if (/404 \(Not Found\)/.test(text)) return;
      /**
       * The browser logs every 4xx as "Failed to load resource", carrying no
       * URL — so a permission denial and a real fault look identical here and
       * neither can be acted on. The response handler below sees the URL and
       * classifies properly; these duplicates are dropped so they cannot bury
       * it.
       */
      if (/Failed to load resource/i.test(text)) return;
      record('high', user.label, screen, 'console', text.slice(0, 180));
    });

    page.on('response', (res) => {
      const status = res.status();
      if (status < 400) return;

      /**
       * A denial is the permission system working — but which endpoint refused
       * is worth seeing, because a role being refused its *own* screen is a
       * misconfiguration wearing the same status code. Recorded as low so it
       * is legible without competing with failures.
       */
      if (isExpectedDenial(status)) {
        if (res.url().includes('/api/')) {
          record('low', user.label, screen, 'denied',
            `403 ${res.request().method()} ${res.url().split('/api/')[1]?.slice(0, 70)}`);
        }
        return;
      }

      /**
       * The first /auth/login carries no second factor, so a 401 there is the
       * challenge being issued — the flow working, not failing.
       */
      if (status === 401 && res.url().includes('/auth/login')) return;

      /**
       * A 404 from /hr/me means the account has no staff record — an expected
       * state the portal explains rather than an error. The browser logs the
       * status regardless, so it is filtered here to keep real failures visible.
       */
      if (status === 404 && /\/hr\/me(\?|$)/.test(res.url())) return;
      const url = res.url();
      if (!url.includes('/api/')) return;
      record(status >= 500 ? 'high' : 'medium', user.label, screen, 'http',
        `${status} ${res.request().method()} ${url.split('/api/')[1]?.slice(0, 70)}`);
    });

    let { signedIn, landedOn } = await signIn(page, user);

    /**
     * One retry, on a fresh time step.
     *
     * A TOTP code may be spent exactly once — the server records the step it
     * accepted and refuses that step and anything earlier — so a code consumed
     * by a previous attempt is correctly rejected. Waiting for the next window
     * before retrying keeps that from reading as a broken sign-in, without
     * masking one: a genuinely broken login fails both times.
     */
    if (!signedIn) {
      const secondsIntoStep = Math.floor(Date.now() / 1000) % 30;
      await page.waitForTimeout((31 - secondsIntoStep) * 1000);
      ({ signedIn, landedOn } = await signIn(page, user));
    }

    if (!signedIn) {
      record('high', user.label, 'login', 'auth', 'Could not sign in');
      console.log(`  ✗ ${user.label.padEnd(14)} sign-in failed`);
      await context.close();
      continue;
    }

    console.log(`  ✓ ${user.label.padEnd(14)} signed in → ${landedOn}`);

    // ── Walk everything this role can see ────────────────────────────────
    /**
     * `aria-expanded` is what separates a collapsible group from a plain link.
     *
     * Menu items render as MUI list buttons rather than anchors, so neither the
     * tag name nor the absence of an href distinguishes them — treating every
     * hrefless item as a group made the harness click its way through the whole
     * menu before it started testing, and it then found nothing to visit.
     */
    const readNav = () =>
      page
        .locator('nav a, [role="navigation"] a, .MuiDrawer-root [role="button"]')
        .evaluateAll((els) =>
          els
            .map((el) => ({
              label: (el.innerText || '').trim().split('\n')[0].slice(0, 30),
              href: el.getAttribute('href'),
              collapsed: el.getAttribute('aria-expanded') === 'false'
            }))
            .filter((x) => x.label)
        );

    const navItems = await readNav();

    /**
     * Expand every collapsible group first.
     *
     * Grouped items — HR & Payroll, Guest Portal — render their children only
     * once opened, so a closed group counted as one "visited" screen and the
     * pages inside it were never reached at all.
     */
    for (const item of navItems.filter((x) => x.collapsed)) {
      const group = page.getByRole('button', { name: item.label, exact: true }).first();
      if (await group.isVisible().catch(() => false)) {
        await group.click({ timeout: 3000 }).catch(() => null);
        await page.waitForTimeout(400);
      }
    }

    const expanded = await readNav();

    const seen = new Set();
    let visited = 0;

    for (const item of expanded) {
      if (seen.has(item.label) || !item.label) continue;
      seen.add(item.label);

      screen = item.label;
      try {
        const control = page.getByRole('button', { name: item.label, exact: true })
          .or(page.getByRole('link', { name: item.label, exact: true }))
          .first();

        /**
         * Groups collapse again on navigation, so a child that was visible when
         * the menu was first read has disappeared by the time its turn comes.
         * Re-open anything collapsed and look once more before giving up —
         * otherwise every screen inside a group is silently skipped.
         */
        if (!(await control.isVisible().catch(() => false))) {
          for (const group of await readNav()) {
            if (!group.collapsed) continue;
            await page
              .getByRole('button', { name: group.label, exact: true })
              .first()
              .click({ timeout: 3000 })
              .catch(() => null);
            await page.waitForTimeout(350);
          }
        }

        if (!(await control.isVisible().catch(() => false))) continue;

        await control.click({ timeout: 5000 });
        await page.waitForTimeout(HEADED ? 900 : 550);
        visited += 1;

        /**
         * Let the screen settle before judging it.
         *
         * Some routes check for an open shift before rendering and redirect if
         * there is none, so a fixed pause can land on the loading spinner —
         * which reads as a blank screen and reported a working guard as a
         * broken page. Waiting for the loader to clear, and for the network to
         * go quiet, measures the screen the user actually ends up on.
         */
        await page
          .locator('text=/checking shift|loading/i')
          .first()
          .waitFor({ state: 'hidden', timeout: 6000 })
          .catch(() => null);
        await page.waitForLoadState('networkidle', { timeout: 6000 }).catch(() => null);

        // A screen that renders nothing is a broken screen, whatever the
        // network did.
        const text = (await page.locator('main, body').first().innerText().catch(() => '')) || '';
        if (text.trim().length < 60) {
          record('high', user.label, item.label, 'render', 'Screen rendered almost nothing');
        }

        // An error boundary catching a crash.
        if (/something went wrong|unexpected error|chunk load/i.test(text)) {
          record('high', user.label, item.label, 'crash', text.trim().slice(0, 120));
        }
      } catch {
        // A nav item that cannot be clicked is worth knowing about, but a
        // collapsed group heading is not a failure.
      }
    }

    console.log(`     visited ${visited} screen(s)`);
    await page.screenshot({ path: path.join(SHOTS, `role-${user.label}.png`), fullPage: false });
    await context.close();
  }

  await browser.close();

  // ── Report ──────────────────────────────────────────────────────────────
  const by = { high: [], medium: [], low: [] };
  for (const f of findings) by[f.severity].push(f);

  console.log('\n' + '─'.repeat(74));
  console.log(`FINDINGS: ${by.high.length} high · ${by.medium.length} medium · ${by.low.length} low`);
  console.log('─'.repeat(74));

  for (const level of ['high', 'medium', 'low']) {
    if (!by[level].length) continue;
    console.log(`\n${level.toUpperCase()}`);
    const seenKeys = new Set();
    for (const f of by[level]) {
      const key = `${f.role}|${f.screen}|${f.kind}|${f.detail}`;
      if (seenKeys.has(key)) continue;
      seenKeys.add(key);
      console.log(`  [${f.role} · ${f.screen}] ${f.kind}: ${f.detail}`);
    }
  }

  fs.writeFileSync(path.join(process.cwd(), 'e2e', 'role-findings.json'), JSON.stringify(findings, null, 2));
  console.log('\nScreenshots: e2e/screenshots/  ·  Raw: e2e/role-findings.json\n');
};

run().catch((error) => {
  console.error('Run failed:', error.message);
  process.exit(1);
});
