export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  BUSINESS_ADMIN = 'BUSINESS_ADMIN',
  RECEPTIONIST = 'RECEPTIONIST',
  POS_STAFF = 'POS_STAFF',
  HOUSEKEEPING = 'HOUSEKEEPING',
  ACCOUNTANT = 'ACCOUNTANT',
  MANAGER = 'MANAGER'
}

export enum BusinessStatus {
  CREATED = 'CREATED',
  TRIAL = 'TRIAL',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  EXPIRED = 'EXPIRED',
  DELETED = 'DELETED'
}
