import { useEffect, useState } from 'react';
import {
  Alert, Box, Button, Chip, CircularProgress, Paper, Stack,
  Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Typography
} from '@mui/material';
import DownloadRounded from '@mui/icons-material/DownloadRounded';
import GridOnRounded from '@mui/icons-material/GridOnRounded';
import DescriptionRounded from '@mui/icons-material/DescriptionRounded';
import {
  MigrationEntity, TemplateInfo, downloadMigrationTemplate, listMigrationTemplates
} from '../../services/migration.service';

/**
 * Starter files for a bulk import.
 *
 * Placed ahead of the upload step on purpose. Most failed imports are not
 * rejected rows — they are a spreadsheet whose columns never matched anything,
 * and the cheapest moment to fix that is before anyone has typed into it.
 *
 * The files are generated by the server from the same schema the importer
 * validates against, so what is downloaded here cannot drift from what is
 * accepted.
 */

const LABEL: Record<MigrationEntity, string> = {
  GUEST: 'Guests', ROOM: 'Rooms', BOOKING: 'Bookings'
};

const DESCRIPTION: Record<MigrationEntity, string> = {
  GUEST: 'Guest profiles — names, contact details and identification.',
  ROOM: 'The room list — numbers, types, floors and nightly rates.',
  BOOKING: 'Reservations, past and future. Import guests first.'
};

export function MigrationTemplates() {
  const [templates, setTemplates] = useState<TemplateInfo[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [busy, setBusy] = useState<string | null>(null);

  useEffect(() => {
    listMigrationTemplates()
      .then(setTemplates)
      .catch(() => setError('Could not load the template list.'))
      .finally(() => setLoading(false));
  }, []);

  const download = async (entity: MigrationEntity, format: 'csv' | 'xlsx') => {
    setBusy(`${entity}-${format}`);
    setError('');
    try {
      await downloadMigrationTemplate(entity, format);
    } catch {
      setError(`Could not download the ${LABEL[entity]} ${format.toUpperCase()} template.`);
    } finally {
      setBusy(null);
    }
  };

  if (loading) {
    return <Box sx={{ py: 4, textAlign: 'center' }}><CircularProgress size={24} /></Box>;
  }

  return (
    <Paper variant="outlined" sx={{ p: { xs: 2, sm: 3 }, mb: 3 }}>
      <Typography variant="h6" fontWeight={700} gutterBottom>
        Start from a template
      </Typography>
      <Typography color="text.secondary" sx={{ mb: 2 }}>
        Each file carries the exact column names the importer expects, two
        example rows, and a sheet explaining what every column accepts. Fill it
        in, delete the examples, and upload it below.
      </Typography>

      {error && <Alert severity="error" sx={{ mb: 2 }} onClose={() => setError('')}>{error}</Alert>}

      {/*
        Stated once, here, rather than left for the importer to discover. A
        date read the wrong way round is accepted silently and lands the
        booking on the wrong day — far harder to notice than a rejected row.
      */}
      <Alert severity="warning" sx={{ mb: 2 }}>
        Write dates as <strong>YYYY-MM-DD</strong> — for example <code>2026-03-05</code>.
        A date written <code>05/03/2026</code> is read as 3 May, not 5 March, and
        imports without complaint.
      </Alert>

      <TableContainer>
        <Table size="small">
          <TableHead>
            <TableRow>
              <TableCell>Template</TableCell>
              <TableCell>Required columns</TableCell>
              <TableCell align="right">Download</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {templates.map((template) => (
              <TableRow key={template.entity} hover>
                <TableCell sx={{ minWidth: 220 }}>
                  <Typography fontWeight={600}>{LABEL[template.entity]}</Typography>
                  <Typography variant="body2" color="text.secondary">
                    {DESCRIPTION[template.entity]}
                  </Typography>
                </TableCell>
                <TableCell sx={{ maxWidth: 320 }}>
                  <Stack direction="row" spacing={0.5} flexWrap="wrap" useFlexGap>
                    {template.requiredFields.map((field) => (
                      <Chip key={field} size="small" label={field} variant="outlined" color="warning" />
                    ))}
                  </Stack>
                  <Typography variant="caption" color="text.secondary">
                    {template.fields} columns in total — the rest are optional
                  </Typography>
                </TableCell>
                <TableCell align="right">
                  <Stack direction="row" spacing={1} justifyContent="flex-end">
                    <Button
                      size="small" variant="contained" startIcon={<GridOnRounded />}
                      disabled={busy === `${template.entity}-xlsx`}
                      onClick={() => void download(template.entity, 'xlsx')}
                    >
                      Excel
                    </Button>
                    <Button
                      size="small" startIcon={<DescriptionRounded />}
                      disabled={busy === `${template.entity}-csv`}
                      onClick={() => void download(template.entity, 'csv')}
                    >
                      CSV
                    </Button>
                  </Stack>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </TableContainer>

      <Stack direction="row" spacing={1} alignItems="center" sx={{ mt: 2 }}>
        <DownloadRounded fontSize="small" color="disabled" />
        <Typography variant="caption" color="text.secondary">
          Excel includes the instructions sheet and dropdowns for status columns.
          CSV is the same columns, for diffing against an existing export.
        </Typography>
      </Stack>
    </Paper>
  );
}
